#!/bin/bash
set -euo pipefail

if paru -Qi vicinae-bin > /dev/null 2>&1; then
    echo "vicinae already installed"
else
    echo "installing vicinae..."
    paru -S --noconfirm --needed vicinae-bin
fi

systemctl --user enable --now vicinae

