preload = /home/dima/Pictures/Wallpapers/wallpaper.jpeg
wallpaper {
    monitor = eDP-1
    path = /home/dima/Pictures/Wallpapers/wallpaper.jpeg
    fit_mode = cover # or contain, tile, fill (cover is default)
}
splash = false
