add_newline = true

format = """
$directory\
$git_branch\
$time\
$docker\
$fill\
$cmd_duration\
$line_break\
$character"""

[directory]
style = "bold fg:#E5B13A"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
home_symbol = "~"

[git_branch]
symbol = ""
style = "fg:#D4941A"
format = '[$symbol$branch](fg:#D4941A) '

[time]
disabled = false
style = "fg:#9A7010"
format = '[time $time]($style) '
use_12hr = false
time_format = "%H:%M"

[cmd_duration]
min_time = 2000
show_milliseconds = false
style = "fg:#9A7010"
format = '⏱[$duration]($style) '

[fill]
symbol = " "

[character]
success_symbol = "[❯](bold fg:#E5B13A)"
error_symbol = "[❯](bold fg:#FF0000)"
vicmd_symbol = "[❮](bold fg:#D4941A)"
